### ISSUE TITLE
一个OOM问题

### ISSUE THREAD

**Issue by lxqxsyu** [xuexiangjys/RxUtil#2]
java.lang.OutOfMemoryError
pthread_create (1040KB stack) failed: Try again
com.xuexiang.rxutil.rxjava.RxJavaUtils.executeAsyncTask(RxJavaUtils.java)

java.lang.Thread.nativeCreate(Native Method)
--
2 java.lang.Thread.start(Thread.java:1063)
3 java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
4 java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1553)
5 java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:306)
6 java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:503)
7 java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:602)
8 rx.internal.schedulers.NewThreadWorker.scheduleActual(NewThreadWorker.java)
9 rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker.schedule(CachedThreadScheduler.java)
10 rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker.schedule(CachedThreadScheduler.java)
11 rx.internal.operators.OperatorSubscribeOn.call(OperatorSubscribeOn.java)
12 rx.internal.operators.OperatorSubscribeOn.call(OperatorSubscribeOn.java)
13 rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java)
14 rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java)
15 rx.Observable.subscribe(Observable.java)
16 rx.Observable.subscribe(Observable.java)
17 rx.Observable.subscribe(Observable.java)
18 com.xuexiang.rxutil.rxjava.RxJavaUtils.executeAsyncTask(RxJavaUtils.java)
19 com.xuexiang.rxutil.rxjava.RxJavaUtils.executeAsyncTask(RxJavaUtils.java)

**Comment by xuexiangjys** [comment]
你怎么调用的呢？给我看看调用的代码片段 @lxqxsyu

**Comment by lxqxsyu** [comment]
RxJavaUtils.executeAsyncTask

**Comment by xuexiangjys** [comment]
@lxqxsyu 你光给我看这个有什么用，我需要代码片段，你怎么调用的

**Comment by lxqxsyu** [comment]
里面的代码比较复杂了，后来我改成了异步任务了，我再看看其他地方还有这个问题没

**Comment by xuexiangjys** [comment]
我查了一下，使用的RxAndroid的io线程池，这个线程池是一个corePoolSize为1，maxNumber 为 Integer.MAX（也就相当于无穷大),但是keep-alive时间为60s，导致oom的问题是线程创建不销毁，阻塞在那，然后不断创建新线程，超过了极限，最终导致OOM，因此还是书写的姿势不对，或者自定义RxAndroid的io线程池可以解决。 @lxqxsyu

**Comment by xuexiangjys** [comment]
已在demo中增加解决的方法
